### ISSUE TITLE
GET: /api/v1/replace/:resourceType/:primary/:duplicate returns "500 - TypeError: undefined is not a function"

### ISSUE THREAD

**Issue by igiware** [amida-tech/DRE-services#7]
full response

TypeError: undefined is not a function
    at replace (/var/www/files_for_clients/dre/services/lib/dre/index.js:45:18)
    at /var/www/files_for_clients/dre/services/lib/dre/index.js:36:5
    at Layer.handle [as handle_request](/var/www/files_for_clients/dre/services/node_modules/express/lib/router/layer.js:82:5)
    at next (/var/www/files_for_clients/dre/services/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/var/www/files_for_clients/dre/services/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request](/var/www/files_for_clients/dre/services/node_modules/express/lib/router/layer.js:82:5)
    at /var/www/files_for_clients/dre/services/node_modules/express/lib/router/index.js:267:22
    at param (/var/www/files_for_clients/dre/services/node_modules/express/lib/router/index.js:340:14)
    at param (/var/www/files_for_clients/dre/services/node_modules/express/lib/router/index.js:356:14)
    at param (/var/www/files_for_clients/dre/services/node_modules/express/lib/router/index.js:356:14)

**Comment by mhiner** [comment]
Please confirm that your npm modules are up to date.    dre-data should be 0.0.12.

**Comment by igiware** [comment]
With updated dre-data works fine. Thanks a lot.
